name: simulation-dev
channels:
  - defaults
dependencies:
  - jupyterlab=3.4.4
  - matplotlib=3.5.2
  - numpy=1.26.3
  - pandas=1.4.4
  - pip=22.2.2
  - pytest=7.1.2
  - python=3.9.13
  - scipy=1.11.4
  - pip:
    - joblib==1.3.2
    - simpy==4.1.1

